# Generated by Django 5.2.10 on 2026-03-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='ubicacion',
        ),
    ]
