# Generated by Django 5.2.10 on 2026-03-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_bodega_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='fecha',
            new_name='fechaRegistro',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fechaEntrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
