# Generated by Django 5.2.10 on 2026-03-20 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='fechaRegistro',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fechaMovimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
