# Generated by Django 5.2.10 on 2026-03-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_movimiento_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fechaMovimiento',
            field=models.DateField(),
        ),
    ]
