# Generated by Django 5.2.10 on 2026-04-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_movimiento_fechamovimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='fechaEntrega',
        ),
        migrations.AddField(
            model_name='activo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Consumible', 'Consumible')], default='Consumible', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductoActivo',
        ),
    ]
