# Generated by Django 5.2.10 on 2026-02-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
