# Generated by Django 5.2.10 on 2026-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_correo_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
