# Generated by Django 5.2.10 on 2026-02-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
