# Generated by Django 5.2.10 on 2026-03-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
